# Site settings
title: Lewis Williams
subtitle: Gameplay Engineer
name: Lewis Williams
description: >
  Gameplay-focused engineer specialising in player-facing systems,
  gameplay architecture, and real-time interaction using Unreal Engine (C++)
  and Unity (C#).

url: "https://lewisw99.github.io"
baseurl: "/lewis-williams-gameplay"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (required)
plugins:
  - jekyll-include-cache

# Appearance
minimal_mistakes_skin: dark
custom_css:
- /assets/css/custom.css

# Navigation
header_pages:
  - index.md

# Markdown
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: single

  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
